version: '3'

services:
  postgres:
    image: postgres:latest
    container_name: local-db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      PGPASSWORD: password123
      POSTGRES_DB: ausu
      TZ: "Asia/Tokyo"
    ports:
      - 5432:5432
    volumes:
      - ./db:/var/lib/postgresql/data
volumes:
  postgres:
