package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.21 DO NOT EDIT.

import (
	"context"
	"fmt"
	"supporting/apps/supporting-api/graph/model"
)

// RegisterGovernment is the resolver for the registerGovernment field.
func (r *mutationResolver) RegisterGovernment(ctx context.Context, name string) (*model.Government, error) {
	panic(fmt.Errorf("not implemented: RegisterGovernment - registerGovernment"))
}

// Governments is the resolver for the governments field.
func (r *queryResolver) Governments(ctx context.Context) ([]*model.Government, error) {
	panic(fmt.Errorf("not implemented: Governments - governments"))
}
